AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: TeamBoard - Lambda de métricas

Resources:

  MetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: teamboard-metrics
      CodeUri: metrics/
      Handler: app.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 256
      

      Environment:
        Variables:
          DB_HOST: host.docker.internal
          DB_PORT: 5432
          DB_NAME: teamboard
          DB_USER: teamboard
          DB_PASSWORD: teamboard2026
      
      Events:
        MetricsApi:
          Type: Api
          Properties:
            Path: /metrics
            Method: get